#### Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

nola
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]

In [ ]:
# Solution 
import numpy as np
# 4 rows and 7 column array initialize
# arange creates even spaced array
a = np.arange(start=1,stop= 65,step =2)
print(a)

#Reshape this to array
b = a.reshape(4,8)
print(b)

# slicing to remove last column
c = b[:, :-1]
print(c)





In [10]:
#### Create a following pattern without hardcoding.Use only numpy functions 
# Input a = np.array([1,2,3])
# Output : array [1,1,1,2,2,2,3,3,3,1,2,3,1,2,3]
import numpy as np
a = np.array([1,2,3])
b = np.arange(10,30)
print (a)
print(b)

# Repeat Function 
d = np.repeat(a,3)
print(d)

# Arreay reap itself
s = np.tile(a,2)
print(s)

g = np.concatenate((d,s))
print(g)

[1 2 3]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
