# Numpy Exercise with solutions

In [2]:
import numpy as np 

In [7]:
#### 1:  Create  null vector of size 10 of which fifth value is (1)

# Sol:
a = np.zeros([10])
print(a)

a[4] = 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### Make an array immutable (read-only) 
# sol
# Created an array
a = np.zeros([10])
print (a)
# set the writable to false makes array immutable. Any modification will result in error.
a.flags.writable = False
z[0] = 1 # Modifying the array result in value error


In [17]:
#### 3: Reverse a vector (first Element becomes last)

#sol: (Use flip to reverse array)
h = np.array([10,20,40])
print(h)
h = np.flip([10,20,30])
print(h)

z = np.arange(10,50)
print(z)
g = np.flip(z)
print(g)
g = z[::-1] # 2nd Solution
print(g)


[10 20 40]
[30 20 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [26]:
#### 4. Create a 3x3 matrix with values ranging from 0 to 8

#sol To create Matrix 
m=np.array((0,1,2,3,4,5,6,7,8))
new_arr= m.reshape(3,3)
print(new_arr)
print(m)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [ ]:
#### . What are the results of the following expressions
# np.array(0)/np.array(0)  -nan
# np.array(0) //np.array(0) - 0 
# np.array([np.nan]).astype(int).astype(float)  REsult[[-9.22337204e+18]]

#sol.
a = np.array(0) 
b = np.array(0)

c = a/b 
print(c)

c = a//b 
print(c)

h = np.array([np.nan]).astype(int).astype(float)
# np.nan = not a number create a array with one not a number value
# astype(int)  converts float to int & astype(float) int to float
print(h)


In [ ]:
####. How to find common values between array
# sol

# Create two random array
a = np.random.randomint[(10,10,4)]
b = np.random.randomint([10,10,4])
print(a)
print(b)

d = np.intersect1d(a,b) #Common value
print(d)




In [38]:
#### 5. Find indices of Non Zero Element from [1,2,0,0,4,0]
# sol. We can use nonzero to find 

j = np.nonzero([1,2,0,0,4,0])
print(j)



(array([0, 1, 4]),)


In [42]:
#### 6 Create a 3x3 identity matrix 

#sol. 
s = np.identity(3)
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
#### 7 Create a 3x3x3 array with random values 
# sol.

new = np.random.random((3,3,3))
print(new)

[[[0.55357436 0.51891011 0.26686042]
  [0.87461293 0.20964761 0.58084062]
  [0.35759948 0.19798549 0.99342408]]

 [[0.661671   0.2993363  0.6614088 ]
  [0.59119888 0.1095634  0.70337228]
  [0.75835868 0.01027112 0.14379615]]

 [[0.40235374 0.80862339 0.65489984]
  [0.09552856 0.99339556 0.64696703]
  [0.2443489  0.4491325  0.594756  ]]]


In [ ]:
#### 8 Create a 10x10 array with random values and find the minimum and maximum values
# sol.
 
kite = np.random.random(10,10)
print(kite)

max.value = np.max(kite)  # Maximum Value 
min.value = np.min(kite)  # Minimum Value
print(max.value)
print(min.value)

In [ ]:
#### 9 Create a 2D array with 1 on border and 0 inside
#sol.

# Create (x,y) array with 1 border and 0 inside 

arr = np.ones((10,10))
print(arr)

# Now if I replace row & column 1 with 0 inside that I get the desired matrix 

arr[1:-1,1:-1] =0  # Slicing of Array from index 1 to - 1 index
print(arr)

#### How to add a border (filled with 0's) around an existing array? 

# Modifying the array 'x' to set 0s on the border and 1s inside the array using the np.pad function
print("0 on the border and 1 inside in the array")
x = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(x)

In [ ]:
#### 7 Create a random vector of size 30 and find the mean value
# sol.

random_vector = np.random.random(30)
print(random_vector)
mean_value = np.mean(random_vector)
