# Numpy Exercise with solutions

In [2]:
import numpy as np 

In [7]:
#### 1:  Create  null vector of size 10 of which fifth value is (1)

# Sol:
a = np.zeros([10])
print(a)

a[4] = 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#### 2. Create a vector values ranging form 10 to 49

# sol:
b = np.array([10,49])
print(b)

c = np.arange(10,49) #  arange() and np. linspace() are NumPy functions used to 
#generate numerical sequences, but they have some differences in their behavior. 
# arange() generates a sequence of values from start to stop with a given step size 
# linspace generates a sequence of num evenly spaced values from start to stop .

print(c)

d = np.linspace(10,30)
print(d)

[10 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[10.         10.40816327 10.81632653 11.2244898  11.63265306 12.04081633
 12.44897959 12.85714286 13.26530612 13.67346939 14.08163265 14.48979592
 14.89795918 15.30612245 15.71428571 16.12244898 16.53061224 16.93877551
 17.34693878 17.75510204 18.16326531 18.57142857 18.97959184 19.3877551
 19.79591837 20.20408163 20.6122449  21.02040816 21.42857143 21.83673469
 22.24489796 22.65306122 23.06122449 23.46938776 23.87755102 24.28571429
 24.69387755 25.10204082 25.51020408 25.91836735 26.32653061 26.73469388
 27.14285714 27.55102041 27.95918367 28.36734694 28.7755102  29.18367347
 29.59183673 30.        ]


In [17]:
#### 3: Reverse a vector (first Element becomes last)

#sol: (Use flip to reverse array)
h = np.array([10,20,40])
print(h)
h = np.flip([10,20,30])
print(h)

z = np.arange(10,50)
print(z)
g = np.flip(z)
print(g)
g = z[::-1] # 2nd Solution
print(g)


[10 20 40]
[30 20 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [26]:
#### 4. Create a 3x3 matrix with values ranging from 0 to 8

#sol To create Matrix 
m=np.array((0,1,2,3,4,5,6,7,8))
new_arr= m.reshape(3,3)
print(new_arr)
print(m)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [38]:
#### 5. Find indices of Non Zero Element from [1,2,0,0,4,0]
# sol. We can use nonzero to find 

j = np.nonzero([1,2,0,0,4,0])
print(j)



(array([0, 1, 4]),)


In [42]:
#### 6 Create a 3x3 identity matrix 

#sol. 
s = np.identity(3)
print(s)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
#### 7 Create a 3x3x3 array with random values 
# sol.

new = np.random.random((3,3,3))
print(new)

[[[0.55357436 0.51891011 0.26686042]
  [0.87461293 0.20964761 0.58084062]
  [0.35759948 0.19798549 0.99342408]]

 [[0.661671   0.2993363  0.6614088 ]
  [0.59119888 0.1095634  0.70337228]
  [0.75835868 0.01027112 0.14379615]]

 [[0.40235374 0.80862339 0.65489984]
  [0.09552856 0.99339556 0.64696703]
  [0.2443489  0.4491325  0.594756  ]]]


In [ ]:
#### 8 Create a 10x10 array with random values and find the minimum and maximum values
# sol.
 
kite = np.random.random(10,10)
print(kite)

max.value = np.max(kite)  # Maximum Value 
min.value = np.min(kite)  # Minimum Value
print(max.value)
print(min.value)

In [ ]:
#### 9 Create a 2D array with 1 on border and 0 inside
#sol.

# Create (x,y) array with 1 border and 0 inside 

arr = np.ones((10,10))
print(arr)

# Now if I replace row & column 1 with 0 inside that I get the desired matrix 

arr[1:-1,1:-1] =0  # Slicing of Array from index 1 to - 1 index
print(arr)

#### How to add a border (filled with 0's) around an existing array? 

# Modifying the array 'x' to set 0s on the border and 1s inside the array using the np.pad function
print("0 on the border and 1 inside in the array")
x = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(x)

In [ ]:
#### 7 Create a random vector of size 30 and find the mean value
# sol.

random_vector = np.random.random(30)
print(random_vector)
mean_value = np.mean(random_vector)
